# Generated by Django 3.0.3 on 2020-02-06 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0002_auto_20200205_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
